influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "2003:2003"
  env_file:
    - 'env.influxdb'
  volumes:
    - /srv/docker/influxdb/data:/var/lib/influxdb
    - /etc/influxdb/conf/influxdb.conf

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  user: "0"
  links:
    - influxdb
  volumes:
    - /srv/docker/grafana/data:/var/lib/grafana
